Tandelion0/Tandelion0/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tandelion0.Models
{
    public class Project
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectTitle { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime DueDate { get; set; }
        public int Timeline { get; set; }
        public string client { get; set; }
        public int? NoTrade { get; set; }
        //public virtual CreateAccount CreateAccount { get; set; }
        public virtual ICollection<Trade> Trade { get; set; }
        
    }
}

Tandelion0/Tandelion0/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tandelion0.DAL;
using Tandelion0.Models;

namespace Tandelion0.Controllers
{
    public class ProjectsController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Projects
        public ActionResult Index()
        {
            // TradeNumber = new db.tradesDB();
            
            var TradesNumber = db.tradesDB.Where(xm=>xm.TradeType!="").ToList().Count() ;

            foreach (var lm in db.projectsDB.ToList())
            {
                //lm.NoTrade = TradesNumber;
                lm.NoTrade = TradesNumber;
            }
            
            return View(db.projectsDB.ToList());
           
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.projectsDB.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjectName,ProjectTitle,DueDate,Timeline,StartDate,client,NoTrade")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.projectsDB.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.projectsDB.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProjectName,ProjectTitle,DueDate,Timeline,StartDate,client,NoTrade")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.projectsDB.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.projectsDB.Find(id);
            db.projectsDB.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tandelion0/Tandelion0/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tandelion0.DAL;
using Tandelion0.Models;

namespace Tandelion0.Controllers
{
    public class TradesController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Trades
        //why viewmodel must be used?
        public ActionResult Index(Project viewmodel, int? id)
        {
            //projectmatch = db.projectsDB.Find(ID);
            var tradesDB = db.tradesDB.Include(t => t.Project);
            
            //.First(vm=>vm.ProjectID==projectmatch.ID);
            //Console.WriteLine(tradesDB.ID)
            List<Trade> test = new List<Trade>();
            //var projectkDB;
            foreach (var item in tradesDB)
            {
                if (item.ProjectID == id || id == null)
                {
                    //item.projectName = ProjectName; **
                    test.Add(item);
                    
                    //ProjectName.FirstOrDefault();
                    
                }
                
                //ViewBag.bit = ProjectName.First();
                
            }
            //var projectkDB = db.projectsDB.Where(vm => vm.ID == id).First();
            
            
            if(id==null)
                ViewBag.Title = "Trade";
            else
            {
                var projectkDB = db.projectsDB.Where(vm => vm.ID == id).First();
                ViewBag.Title = projectkDB.ProjectName.ToString();
            }
                

            return View(test);
        }


        // GET: Trades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.tradesDB.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // GET: Trades/Create
        public ActionResult Create()
        {
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName");
            return View();
        }

        // POST: Trades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TradeType,StartDate,Progress,DueDate,ProjectID,TendererNo")] Trade trade)
        {

            if (ModelState.IsValid)
            {
                db.tradesDB.Add(trade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", trade.ProjectID);
            return View(trade);
        }

        // GET: Trades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.tradesDB.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", trade.ProjectID);
            return View(trade);
        }

        // POST: Trades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TradeType,StartDate,Progress,DueDate,ProjectID,TendererNo")] Trade trade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", trade.ProjectID);
            return View(trade);
        }

        // GET: Trades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.tradesDB.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // POST: Trades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trade trade = db.tradesDB.Find(id);
            db.tradesDB.Remove(trade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tandelion0/Tandelion0/Views/Projects/Create.cshtml
@model Tandelion0.Models.Project

@{
    ViewBag.Title = "Create";
}

<style>
    p.ex1 {
        padding: 1cm;
    }

    H2.ex1 {
        padding: 1cm;
    }

    .editor-field textarea {
        width: 400px;
        height: 200px;
    }
</style>

<h2 class="ex1" align="center">Create New Project</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">
            <!-- Left half -->
            <div class="col-md-6" align="center">
                <p>
                    <img src="~/Image/New Project/Rocket.jpg" alt="Alternate Text" width=400 height=300 />
                    <!--img src="img/other img/rocket.jpg" width="400px" height="300px">-->
                </p>
                <h4 align="center">Your journey begins here</h4>
            </div>

            <div class="form-horizontal">
                <div class="container">
                    <div class="row justify-content-md-center" style="height: 100px">
                        <div class="col-md-6 jumbotron">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @* Project Name *@
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12">
                                    <h5>Project Name</h5>
                                    @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @* Client    *@
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.client, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12">
                                    <h5>Client</h5>
                                    @Html.EditorFor(model => model.client, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                                    @Html.ValidationMessageFor(model => model.client, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @* Project title *@
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.ProjectTitle, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12 editor-field">
                                    <h5>Project Title</h5>
                                    @*@Html.EditorFor(model => model.ProjectTitle, new { htmlAttributes = new { @class = "form-control" } })*@
                                    @Html.TextAreaFor(model => model.ProjectTitle, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                                    @Html.ValidationMessageFor(model => model.ProjectTitle, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <hr />
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Timeline, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12">
                                    <h5>Timeline</h5>
                                    @Html.EditorFor(model => model.Timeline, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Timeline, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12">
                                    <h5>Start Date</h5>
                                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12">
                                    <h5>Due Date</h5>
                                    @Html.TextBoxFor(model => model.DueDate, new { @class = "form-control", placeholder = "Due date here..." })
                                    @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                @*@Html.LabelFor(model => model.NoTrade, htmlAttributes: new { @class = "control-label col-md-3" })*@
                                <div class="col-md-12">
                                    <h5>No of Trade</h5>
                                    @Html.EditorFor(model => model.NoTrade, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NoTrade, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="container" align="center">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

Tandelion0/Tandelion0/Views/Projects/Delete.cshtml
@model Tandelion0.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timeline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timeline)
        </dd>

        
        <dt>
            @Html.DisplayNameFor(model => model.client)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoTrade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoTrade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tandelion0/Tandelion0/Views/Projects/Details.cshtml
@model Tandelion0.Models.Project

@{
    ViewBag.Title = "Details";
}

<h3>@Html.DisplayFor(model => model.ProjectName)</h3>

<h5>@Html.DisplayFor(model => model.client)</h5>

<style>
    p.ex1 {
        padding: 1cm 2.5cm 0cm 2.5cm;
    }
</style>

<div>
    <hr />
    <div align="center" height="400px">
        <img src="~/Image/Project/Ecohill.jpg" width="500" height="300" alt="" align="middle">
    </div>

    <p class="ex1">
        @Html.DisplayFor(model => model.ProjectTitle)
    </p>

    @*<dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayName("Project Name")
        </dt>*@
        @*<dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>*@

        @*<dt>
            @Html.DisplayName("Client")
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.client)
        </dd>*@

        @*<dt>
            @Html.DisplayName("Project Title")
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.ProjectTitle)
        </dd>*@
    @*</dl>*@

        <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Start Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        @*<dt>
            @Html.DisplayName("Timeline")
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.Timeline)
        </dd>*@

        <dt>
            @Html.DisplayName("Due Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>



        @*<dt>
            @Html.DisplayName("No of Trade")
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.NoTrade)
        </dd>*@

      </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tandelion0/Tandelion0/Views/Projects/Edit.cshtml
@model Tandelion0.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Timeline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Timeline, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Timeline, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Timeline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Timeline, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Timeline, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.client, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.client, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.client, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoTrade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoTrade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoTrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tandelion0/Tandelion0/Views/Projects/Index.cshtml
@model IEnumerable<Tandelion0.Models.Project>

@{
    ViewBag.Title = "Project";
}


<h2>@ViewBag.Title</h2>

<p Align="right">
    @Html.ActionLink("Create New Project", "Create", "ControllerName", new { @class = "btn btn-primary" })
</p>
<table class="table table-hover">
    <thead>
    <tr>
        <th>

        </th>
        <th scope="col" width="200">
            @Html.DisplayName("Project Name")
            @*@Html.DisplayNameFor(model => model.ProjectName)*@
        </th>
        @*<th scope="col" width="200">
            @Html.DisplayName("Project Title")
            @Html.DisplayNameFor(model => model.ProjectTitle)
        </th>*@
        <th scope="col" width="100">
            @Html.DisplayName("Client")
            @*@Html.DisplayNameFor(model => model.client)*@
        </th>
        <th>
            @Html.DisplayName("No of Trade")
            @*@Html.DisplayNameFor(model => model.NoTrade)*@
        </th>
        <th>
            @Html.DisplayName("Start Date")
            @*@Html.DisplayNameFor(model => model.StartDate)*@
        </th>
        <th>
            @Html.DisplayName("Due Date")
            @*@Html.DisplayNameFor(model => model.DueDate)*@
        </th>
        <th scope="col" width="150">
            @Html.DisplayName("Timeline")
            @*@Html.DisplayNameFor(model => model.Timeline)*@
        </th>
        
        <th></th>
    </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr onclick="document.location = '@Url.Action( "Index", "Trades",  new { id = item.ID , ProjectName = item.ProjectName}, null) ';">
                <td><img src="~/Image/Project/Ecohill.jpg" alt="" border="3" height="30" width="60"></td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectName)
                </td>
                @*<td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">
                    @Html.DisplayFor(modelItem => item.ProjectTitle)
                </td>*@
                <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">
                    @Html.DisplayFor(modelItem => item.client)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoTrade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Timeline)*@
                    <div class='progress progress-striped'>
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 80%;">
                            Progress
                        </div>
                    </div>
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |*@
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                </td>
            </tr>
        </tbody>
            }

</table>