Tandelion0/Tandelion0/Models/Tender.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tandelion0.Models
{
    public class Tender
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        //CompanyName refer from CreateAccount or CreateTender 
        //bind PICName, PICContactNo, Designation, CompanyContactNo
        public List<CreateAccount> FrequentCompanyName { get; set; }
        public List<CreateAccount> SuggestCompanyName { get; set; }
        public List<CreateAccount> SelectedCompanyName { get; set; }
        public List<CreateAccount> AllCompanyName { get; set; }
        public string Status { get; set; }
        public string PICName { get; set; }
        //PICName refer from CreateAccount
        public Decimal PICContactNo { get; set; }
        //PICContactNo refer from CreateAccount
        public string Designation { get; set; }
        //Designation refer from CreateAccount
        public Decimal CompanyContactNo { get; set; }
        //CompanyContactNo refer from CreateAccount
        
        public int? ProjectID { get; set; }
        public int? TradeID { get; set; }
        public int? CreateAccountID { get; set; }
        public virtual Trade Trade { get; set; }
        //to import TradeType from Trade 
        //public virtual CreateAccount CreateAccount { get; set; }
        public virtual Project Project { get; set; }
        //to import ProjectName from Project
        //public ICollection<Invitation> Invitation { get; set; }
        public virtual CreateAccount CreateAccount { get; set; }

    }
}

Tandelion0/Tandelion0/Controllers/InvitationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tandelion0.DAL;
using Tandelion0.Models;

namespace Tandelion0.Controllers
{
    public class InvitationsController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Invitations
        public ActionResult Index()
        {
            var invitationDB = db.invitationDB.Include(i => i.Project).Include(i => i.Tender);
            return View(invitationDB.ToList());
        }

        // GET: Invitations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invitation invitation = db.invitationDB.Find(id);
            if (invitation == null)
            {
                return HttpNotFound();
            }
            return View(invitation);
        }

        // GET: Invitations/Create
        public ActionResult Create()
        {
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName");
            ViewBag.TenderID = new SelectList(db.tendersDB, "ID", "CompanyName");
            return View();
        }

        // POST: Invitations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Message,TenderID,ProjectID")] Invitation invitation)
        {
            if (ModelState.IsValid)
            {
                db.invitationDB.Add(invitation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", invitation.ProjectID);
            ViewBag.TenderID = new SelectList(db.tendersDB, "ID", "CompanyName", invitation.TenderID);
            return View(invitation);
        }

        // GET: Invitations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invitation invitation = db.invitationDB.Find(id);
            if (invitation == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", invitation.ProjectID);
            ViewBag.TenderID = new SelectList(db.tendersDB, "ID", "CompanyName", invitation.TenderID);
            return View(invitation);
        }

        // POST: Invitations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Message,TenderID,ProjectID")] Invitation invitation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invitation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", invitation.ProjectID);
            ViewBag.TenderID = new SelectList(db.tendersDB, "ID", "CompanyName", invitation.TenderID);
            return View(invitation);
        }

        // GET: Invitations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invitation invitation = db.invitationDB.Find(id);
            if (invitation == null)
            {
                return HttpNotFound();
            }
            return View(invitation);
        }

        // POST: Invitations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invitation invitation = db.invitationDB.Find(id);
            db.invitationDB.Remove(invitation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tandelion0/Tandelion0/Controllers/TendersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tandelion0.DAL;
using Tandelion0.Models;

namespace Tandelion0.Controllers
{
    public class TendersController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Tenders
        public ActionResult Index(Trade viewmodel, int? id)
        {
            //projectmatch = db.projectsDB.Find(ID);
            var TendersDB = db.tendersDB.Include(t => t.Trade);
            //var CreateAccsDB = db.createaccountDB.Include(tm => tm.Trade);

            //List<CreateAccount> AllCompanyName = new List<CreateAccount>();
            //List<CreateAccount> FrequentCompanyname = new List<CreateAccount>();
            
            List<Tender> test = new List<Tender>();
                        
            //test.PICName = CreateAccsDB.ToList().PICName;
            //test.First().CompanyName = CreateAccsDB.First().CompanyName;
            foreach (var item in test)
            {
                //item.PICName = CreateAccsDB.ToList().PICName.First();
                //ViewBag.bit = ProjectName.First();
            }
            
            foreach (var item in TendersDB)
            {
                if (item.TradeID == id || id == null)
                {
                    //item.projectName = ProjectName; **
                    test.Add(item);
                    //ProjectName.FirstOrDefault();
                }
                //ViewBag.bit = ProjectName.First();
            }
           
            if (id == null)
                ViewBag.Title = "Tenderer";
            else
            {
                var tradekDB = db.tradesDB.Where(vm => vm.ID == id).First();
                ViewBag.Title = tradekDB.TradeType.ToString();
            }

            //var tendersDB = db.tendersDB.Include(t => t.Trade);
            //return View(tendersDB.ToList());
            return View(test);
        }

        // GET: Tenders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tender = db.tendersDB.Find(id);
            if (tender == null)
            {
                return HttpNotFound();
            }
            return View(tender);
        }

        // GET: Tenders/Create
        public ActionResult Create()
        {
            Tender viewmodel = new Tender();

            //var tendersDB = db.tendersDB.Include(t => t.Trade);
            //return View(tendersDB.ToList());

            //var CreateAccsDB = db.createaccountDB.Include(tm => tm.Trade);

            //List<CreateAccount> AllCompanyName = new List<CreateAccount>();

            //AllCompanyName = CreateAccsDB.Where(tm => tm.TradeID == id).ToList();

            //ViewBag.FrequentCompanyName = db.createaccountDB.Where(td=>td.TradeID == 2).Where(tm => tm.Frequency == 2).ToList();

            //ViewBag.SuggestCompanyName = AllCompanyName.Where(tm => tm.Rating == 3).ToList();
            viewmodel.FrequentCompanyName = db.createaccountDB.Include(tm => tm.Trade).Where(td => td.Frequency == 32).ToList();
            viewmodel.SuggestCompanyName = db.createaccountDB.Include(tm => tm.Trade).ToList();

            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType");
            //ViewBag.BB = new List(db.tradesDB, "ID", "TradeType");
            ViewBag.createaccountID = new SelectList(db.createaccountDB, "ID", "CompanyName");
            return View(viewmodel);
            
        }

        // POST: Tenders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CompanyName,Status,PIC,Designation,HP,ContactNo,TradeID,FrequentCompanyName,CreateAccountID")] Tender tender, Tender viewmodel)
        {
            //Tender supermodel = new Tender();
            if (ModelState.IsValid)
            {
                db.tendersDB.Add(tender);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Tender viewmodel = new Tender();
            //viewmodel.FrequentCompanyName = db.createaccountDB.Include(tm => tm.Trade).Where(tm => tm.TradeID == 2).ToList();
            viewmodel.FrequentCompanyName = db.createaccountDB.Include(tm => tm.Trade).Where(td=>td.Rating == 2).ToList();
            viewmodel.SuggestCompanyName = db.createaccountDB.Include(tm => tm.Trade).ToList();
            
            //viewmodel.SuggestCompanyName = db.createaccountDB.Include(tm=)

            //var tendersDB = db.tendersDB.Include(t => t.Trade);
            //return View(tendersDB.ToList());
            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            return View(viewmodel);



            /*

            if (ModelState.IsValid)
            {
                db.tendersDB.Add(tender);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //var CreateAccsDB = db.createaccountDB.Include(tm => tm.Trade);

            //List<CreateAccount> AllCompanyName = new List<CreateAccount>();

            List<CreateAccount> AllCompanyName = db.createaccountDB.Include(tm=>tm.TradeID).Where(tm => tm.TradeID == 2).ToList();

            ViewBag.FrequentCompanyName = AllCompanyName.Where(tm => tm.Frequency == 2).ToList();

            ViewBag.SuggestCompanyName = AllCompanyName.Where(tm => tm.Rating == 3).ToList();

            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            ViewBag.createaccountID = new SelectList(db.createaccountDB, "ID", "CompanyName", tender.CreateAccountID);
            return View(tender);
            */
        }

        // GET: Tenders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tender = db.tendersDB.Find(id);
            if (tender == null)
            {
                return HttpNotFound();
            }
            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            return View(tender);
        }

        // POST: Tenders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CompanyName,Status,PIC,Designation,HP,ContactNo,TradeID")] Tender tender)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tender).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            return View(tender);
        }

        // GET: Tenders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tender = db.tendersDB.Find(id);
            if (tender == null)
            {
                return HttpNotFound();
            }
            return View(tender);
        }

        // POST: Tenders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tender tender = db.tendersDB.Find(id);
            db.tendersDB.Remove(tender);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tandelion0/Tandelion0/Views/Tenders/Create.cshtml
@model Tandelion0.Models.Tender

@{
    ViewBag.Title = "Create";
}

<style>
    p.ex1 {
        padding: 0.5cm 0cm 0cm 0cm;
    }

    sel {
        background-color: #ffd659;
    }
</style>

<script>
    $("tr").not(':first').hover(

   function () {
       if (!$(this).hasClass("sel")) {
           $(this).css("background", "#FFEFC6");
       }
   },
  function () {
      if (!$(this).hasClass("sel")) {
          $(this).css("background", "");
      }
  }

);

    $("tr").click(function (e) {
        $(this).css("background-color", "#ffd659");
        //$("tr:eq("+$(this).index()+")").off("hover");

        $(this).addClass("sel");
    });
</script>

<h2>Select Tenderer</h2>

<div>
    <p Align="right">
        <button type="button" class="btn btn-primary">Proceed to Summary</button>
    </p>
</div>

<div class="row">
    <div class="col-sm-1" align="left">
        <img src="~/Image/Project/Ecohill.jpg" alt="" border="3" height="60" width="100">
    </div>
    <div class="col-sm-3">
        <dl class="dl-horizontal">
            <dt>
                Project
            </dt>
            <dd>
                Ecohill
            </dd>
            <dt>
                Trade
            </dt>
            <dd>
                Drainage
            </dd>

        </dl>
    </div>

</div>

<h4>Insert Subcon Email</h4>
<div>
    <input type="text" class="form-control" placeholder="Selected Subcon's Email" aria-label="Recipient's username" aria-describedby="basic-addon2">
    <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button">Add to Selected Subcon list</button>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container row">
        <!--selected subcon column-->
        <div class="container row col-sm-4">
            <h4>
                Selected Subcon
            </h4>
            
            <div style="overflow-y: scroll; height:250px;">
                <table class="table table-hover">

                    <tbody>
                        
                    </tbody>
                </table>
            </div>
        </div>

        <!--frequent subcon column-->
        <div class="container col-sm-4">
            <h4>
                Recently Selected Subcon
            </h4>
            
            <div style="overflow-y: scroll; height:250px;">
                <table class="table table-hover">
                    
                    @foreach (var item in Model.FrequentCompanyName)
                    {
                        <tbody>
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CompanyName)
                                </td>
                                
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
            <p class="ex1" align="center">
                <a href="#">Select All</a>
                @*<button type="button" class="btn btn-primary">Select All</button>*@
            </p>
        </div>

        <!--Suggested subcon column-->
        <div class="container col-sm-4">
            <h4>
                Recommended Subcon
            </h4>
            @*<hr width="90%" align="left" />*@
            @*<h5 align="center">Company name | Person-in-charge</h5>*@
            <div style="overflow-y: scroll; height:250px;">
                <table class="table table-hover">
                    @foreach (var item in Model.SuggestCompanyName)
                    {
                        <tbody>
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CompanyName)
                                </td>
                                
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
        </div>
    </div>
       
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tandelion0/Tandelion0/Views/Tenders/Delete.cshtml
@model Tandelion0.Models.Tender

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tender</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Trade.TradeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trade.TradeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PICName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PICName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PICContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PICContactNo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tandelion0/Tandelion0/Views/Tenders/Details.cshtml
@model Tandelion0.Models.Tender

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tender</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Trade.TradeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trade.TradeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PICName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PICName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PICContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PICContactNo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tandelion0/Tandelion0/Views/Tenders/Edit.cshtml
@model Tandelion0.Models.Tender

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tender</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PICName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PICName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PICName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PICContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PICContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PICContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TradeID, "TradeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TradeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TradeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tandelion0/Tandelion0/Views/Tenders/Index.cshtml
@model IEnumerable<Tandelion0.Models.Tender>

@{
    ViewBag.Title = "Tender";
}

<h2>@ViewBag.Title</h2>

    <p>
        @Html.ActionLink("Create New Invitation", "Create")
    </p>
    <table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Trade Type")
                @*@Html.DisplayNameFor(model => model.Trade.TradeType)*@
            </th>
            <th scope="col" width="200">
                @Html.DisplayName("Subcon Name")
                @*@Html.DisplayNameFor(model => model.CompanyName)*@
            </th>
            <th>
                @Html.DisplayName("Person in Charge")
                @*@Html.DisplayNameFor(model => model.PICName)*@
            </th>
            <th>
                @Html.DisplayName("Designation")
                @*@Html.DisplayNameFor(model => model.Designation)*@
            </th>
            <th>
                @Html.DisplayName("Contact No")
                @*@Html.DisplayNameFor(model => model.CompanyContactNo)*@
            </th>
            <th>
                @Html.DisplayName("PIC HP")
                @*@Html.DisplayNameFor(model => model.PICContactNo)*@
            </th>
            <th>
                @Html.DisplayName("Status")
                @*@Html.DisplayNameFor(model => model.Status)*@
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
            {
        <tbody>
            <tr onclick="document.location = '@Url.Action( "Index", "Invitations") ';">
                <td>
                    @Html.DisplayFor(modelItem => item.Trade.TradeType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PICName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Designation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyContactNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PICContactNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
            </tbody>
            }

    </table>