Tandelion0/Tandelion0/Models/Trade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tandelion0.Models
{
    public class Trade
    {
        public int ID { get; set; }
        public string TradeType { get; set; }
        //TradeTypr can be selected from CreateAccount
        public DateTime StartDate { get; set; }
        public DateTime DueDate { get; set; }
        public int Progress { get; set; }
        public int? TendererNo { get; set; }
        //refer from Tenderer 
        public int? ProjectID { get; set; }
        public int? CreateAccountID { get; set; }
        //refer from Project

        //public string projectName { get; set; } **
        //interface
        public virtual Project Project { get; set; }
        //public virtual CreateAccount CreateAccount { get; set; }
        public virtual ICollection<CreateAccount> CreateAccount { get; set; }
        public virtual ICollection<Tender> Tender { get; set; }
        
    }
}

Tandelion0/Tandelion0/Controllers/TendersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tandelion0.DAL;
using Tandelion0.Models;

namespace Tandelion0.Controllers
{
    public class TendersController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Tenders
        public ActionResult Index(Trade viewmodel, int? id)
        {
            //projectmatch = db.projectsDB.Find(ID);
            var TendersDB = db.tendersDB.Include(t => t.Trade);
            //var CreateAccsDB = db.createaccountDB.Include(tm => tm.Trade);

            //List<CreateAccount> AllCompanyName = new List<CreateAccount>();
            //List<CreateAccount> FrequentCompanyname = new List<CreateAccount>();
            
            List<Tender> test = new List<Tender>();
                        
            //test.PICName = CreateAccsDB.ToList().PICName;
            //test.First().CompanyName = CreateAccsDB.First().CompanyName;
            foreach (var item in test)
            {
                //item.PICName = CreateAccsDB.ToList().PICName.First();
                //ViewBag.bit = ProjectName.First();
            }
            
            foreach (var item in TendersDB)
            {
                if (item.TradeID == id || id == null)
                {
                    //item.projectName = ProjectName; **
                    test.Add(item);
                    //ProjectName.FirstOrDefault();
                }
                //ViewBag.bit = ProjectName.First();
            }
           
            if (id == null)
                ViewBag.Title = "Tenderer";
            else
            {
                var tradekDB = db.tradesDB.Where(vm => vm.ID == id).First();
                ViewBag.Title = tradekDB.TradeType.ToString();
            }

            //var tendersDB = db.tendersDB.Include(t => t.Trade);
            //return View(tendersDB.ToList());
            return View(test);
        }

        // GET: Tenders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tender = db.tendersDB.Find(id);
            if (tender == null)
            {
                return HttpNotFound();
            }
            return View(tender);
        }

        // GET: Tenders/Create
        public ActionResult Create()
        {
            Tender viewmodel = new Tender();

            //var tendersDB = db.tendersDB.Include(t => t.Trade);
            //return View(tendersDB.ToList());

            //var CreateAccsDB = db.createaccountDB.Include(tm => tm.Trade);

            //List<CreateAccount> AllCompanyName = new List<CreateAccount>();

            //AllCompanyName = CreateAccsDB.Where(tm => tm.TradeID == id).ToList();

            //ViewBag.FrequentCompanyName = db.createaccountDB.Where(td=>td.TradeID == 2).Where(tm => tm.Frequency == 2).ToList();

            //ViewBag.SuggestCompanyName = AllCompanyName.Where(tm => tm.Rating == 3).ToList();
            viewmodel.FrequentCompanyName = db.createaccountDB.Include(tm => tm.Trade).Where(td => td.Frequency == 32).ToList();
            viewmodel.SuggestCompanyName = db.createaccountDB.Include(tm => tm.Trade).ToList();

            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType");
            //ViewBag.BB = new List(db.tradesDB, "ID", "TradeType");
            ViewBag.createaccountID = new SelectList(db.createaccountDB, "ID", "CompanyName");
            return View(viewmodel);
            
        }

        // POST: Tenders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CompanyName,Status,PIC,Designation,HP,ContactNo,TradeID,FrequentCompanyName,CreateAccountID")] Tender tender, Tender viewmodel)
        {
            //Tender supermodel = new Tender();
            if (ModelState.IsValid)
            {
                db.tendersDB.Add(tender);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Tender viewmodel = new Tender();
            //viewmodel.FrequentCompanyName = db.createaccountDB.Include(tm => tm.Trade).Where(tm => tm.TradeID == 2).ToList();
            viewmodel.FrequentCompanyName = db.createaccountDB.Include(tm => tm.Trade).Where(td=>td.Rating == 2).ToList();
            viewmodel.SuggestCompanyName = db.createaccountDB.Include(tm => tm.Trade).ToList();
            
            //viewmodel.SuggestCompanyName = db.createaccountDB.Include(tm=)

            //var tendersDB = db.tendersDB.Include(t => t.Trade);
            //return View(tendersDB.ToList());
            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            return View(viewmodel);



            /*

            if (ModelState.IsValid)
            {
                db.tendersDB.Add(tender);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //var CreateAccsDB = db.createaccountDB.Include(tm => tm.Trade);

            //List<CreateAccount> AllCompanyName = new List<CreateAccount>();

            List<CreateAccount> AllCompanyName = db.createaccountDB.Include(tm=>tm.TradeID).Where(tm => tm.TradeID == 2).ToList();

            ViewBag.FrequentCompanyName = AllCompanyName.Where(tm => tm.Frequency == 2).ToList();

            ViewBag.SuggestCompanyName = AllCompanyName.Where(tm => tm.Rating == 3).ToList();

            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            ViewBag.createaccountID = new SelectList(db.createaccountDB, "ID", "CompanyName", tender.CreateAccountID);
            return View(tender);
            */
        }

        // GET: Tenders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tender = db.tendersDB.Find(id);
            if (tender == null)
            {
                return HttpNotFound();
            }
            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            return View(tender);
        }

        // POST: Tenders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CompanyName,Status,PIC,Designation,HP,ContactNo,TradeID")] Tender tender)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tender).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TradeID = new SelectList(db.tradesDB, "ID", "TradeType", tender.TradeID);
            return View(tender);
        }

        // GET: Tenders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tender = db.tendersDB.Find(id);
            if (tender == null)
            {
                return HttpNotFound();
            }
            return View(tender);
        }

        // POST: Tenders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tender tender = db.tendersDB.Find(id);
            db.tendersDB.Remove(tender);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tandelion0/Tandelion0/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tandelion0.DAL;
using Tandelion0.Models;

namespace Tandelion0.Controllers
{
    public class TradesController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Trades
        //why viewmodel must be used?
        public ActionResult Index(Project viewmodel, int? id)
        {
            //projectmatch = db.projectsDB.Find(ID);
            var tradesDB = db.tradesDB.Include(t => t.Project);
            
            //.First(vm=>vm.ProjectID==projectmatch.ID);
            //Console.WriteLine(tradesDB.ID)
            List<Trade> test = new List<Trade>();
            //var projectkDB;
            foreach (var item in tradesDB)
            {
                if (item.ProjectID == id || id == null)
                {
                    //item.projectName = ProjectName; **
                    test.Add(item);
                    
                    //ProjectName.FirstOrDefault();
                    
                }
                
                //ViewBag.bit = ProjectName.First();
                
            }
            //var projectkDB = db.projectsDB.Where(vm => vm.ID == id).First();
            
            
            if(id==null)
                ViewBag.Title = "Trade";
            else
            {
                var projectkDB = db.projectsDB.Where(vm => vm.ID == id).First();
                ViewBag.Title = projectkDB.ProjectName.ToString();
            }
                

            return View(test);
        }


        // GET: Trades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.tradesDB.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // GET: Trades/Create
        public ActionResult Create()
        {
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName");
            return View();
        }

        // POST: Trades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TradeType,StartDate,Progress,DueDate,ProjectID,TendererNo")] Trade trade)
        {

            if (ModelState.IsValid)
            {
                db.tradesDB.Add(trade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", trade.ProjectID);
            return View(trade);
        }

        // GET: Trades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.tradesDB.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", trade.ProjectID);
            return View(trade);
        }

        // POST: Trades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TradeType,StartDate,Progress,DueDate,ProjectID,TendererNo")] Trade trade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectID = new SelectList(db.projectsDB, "ID", "ProjectName", trade.ProjectID);
            return View(trade);
        }

        // GET: Trades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.tradesDB.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // POST: Trades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trade trade = db.tradesDB.Find(id);
            db.tradesDB.Remove(trade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tandelion0/Tandelion0/Views/Trades/Create.cshtml
@model Tandelion0.Models.Trade

@{
    ViewBag.Title = "Create";
}

<style>
    p.ex1 {
        padding: 1cm;
    }

    H2.ex1 {
        padding: 1cm;
    }

    .editor-field textarea {
        width: 400px;
        height: 200px;
    }
</style>

<h2 class="ex1" align="center">Create New Trade</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">
            <!-- Left half -->
            <div class="col-md-6" align="center">
                <p>
                    <img src="~/Image/New Trade/Trade.jpg" alt="Alternate Text" width=400 height=300 />
                </p>
                <h4 align="center">Your work of art</h4>
            </div>

            <div class="form-horizontal">
                <div class="container">
                    <div class="row justify-content-md-center" style="height: 100px">
                        <div class="col-md-6 jumbotron">

                            <div class="form-group">
                                
                                <div class="col-md-9">
                                    @Html.DisplayName("Project")
                                    @*@Html.LabelFor(model => model.ProjectID, "ProjectID", htmlAttributes: new { @class = "control-label col-md-3" })*@
                                    @Html.DropDownList("ProjectID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                </div>
                            </div>
                                  
                            <div class="form-group">
                                @Html.LabelFor(model => model.TradeType, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.TradeType, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TradeType, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.TendererNo, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TendererNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TendererNo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Progress, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Progress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Progress, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectID, "ProjectID", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("ProjectID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ProjectID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
                  }

                                <div>
                                    @Html.ActionLink("Back to List", "Index")
                                </div>

                                @section Scripts {
                                    @Scripts.Render("~/bundles/jqueryval")
                                }

Tandelion0/Tandelion0/Views/Trades/Delete.cshtml
@model Tandelion0.Models.Trade

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TradeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TradeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TendererNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TendererNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Progress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Progress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tandelion0/Tandelion0/Views/Trades/Details.cshtml
@model Tandelion0.Models.Trade

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Trade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TradeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TradeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TendererNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TendererNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Progress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Progress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tandelion0/Tandelion0/Views/Trades/Edit.cshtml
@model Tandelion0.Models.Trade

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Trade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TradeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TradeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TradeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TendererNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TendererNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TendererNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Progress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Progress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Progress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectID, "ProjectID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tandelion0/Tandelion0/Views/Trades/Index.cshtml
@model IEnumerable<Tandelion0.Models.Trade>




    <h2 id="project_title">
    @*@ViewBag.bit*@
    @*foreach (var item in Model)
    {
        @Html.DisplayFor(modelItem => item.projectName);
        break;
    }*@
        @ViewBag.Title

    </h2>

        <p Align="right">
            @Html.ActionLink("Create New Tender", "Create", "ControllerName", new { @class = "btn btn-primary" })
        </p>

        <h3>Trade list</h3>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>

                    </th>
                    @*<th>
                            @Html.DisplayName("Project Name")
                            Html.DisplayNameFor(model => model.Project.ProjectName)
                        </th>*@
                    <th>
                        @Html.DisplayName("Trade Type")
                        @*@Html.DisplayNameFor(model => model.TradeType)*@
                    </th>
                    <th>
                        @Html.DisplayName("Tender Participants")
                        @*@Html.DisplayNameFor(model => model.TendererNo)*@
                    </th>
                    <th>
                        @Html.DisplayName("Start Date")
                        @*@Html.DisplayNameFor(model => model.StartDate)*@
                    </th>
                    <th>
                        @Html.DisplayName("Due Date")
                        @*@Html.DisplayNameFor(model => model.DueDate)*@
                    </th>
                    <th scope="col" width="150">
                        @Html.DisplayName("Progress")
                        @*@Html.DisplayNameFor(model => model.Progress)*@
                    </th>
                    
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {

                <tbody>
                    <tr onclick="document.location = '@Url.Action( "Index", "Tenders",  new { id = item.ID }, null) ';">

                        <td><img src="~/Image/Trade/Drainage.jpg" alt="" border="3" height="30" width="60"></td>
                        @*<td>
                                @Html.DisplayFor(modelItem => item.Project.ProjectName)
                            </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.TradeType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TendererNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DueDate)
                        </td>
                        <td>
                            <div class='progress progress-striped'>
                                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 80%;">
                                    Progress
                                </div>
                            </div>
                            @*@Html.DisplayFor(modelItem => item.Progress)*@
                        </td>
                        <td>
                            @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |*@
                            @Html.ActionLink("Details", "Details", new { id = item.ID })
                            @*@Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                        </td>
                    </tr>
                </tbody>
            }

            </table>